### PR TITLE
Added Bind DN and Bind Password fields

### PR DESCRIPTION
**Pull request by ahcurrier**
Also added descriptions from
http://framework.zend.com/manual/1.12/en/zend.auth.adapter.ldap.html#zen
d.auth.adapter.ldap.server-options

### CODE REVIEW

**Comment by misilot** [comment]
@ahcurrier when I tried using this PR in 2.2.2 I get the following error: "This is not a valid plugin"

Edit: Figured out the folder needs to be Ldap.

**Comment by misilot** [comment]
This works great for 2.2.2.

**Comment by daveWid** [comment]
Can anyone else confirm this works with version 2.2.2?

Before I merge in the PR you'll need to change the support links back to what they were in plugin.ini and change the version number to 0.4.0 in build.xml and plugin.ini

**Comment by misilot** [comment]
@daveWid I created a PR for @ahcurrier to merge, which would update this PR.

**Comment by ahcurrier** [comment]
Thanks, @daveWid and @misilot. I will make a habit of responding sooner in the future!

**Pull request merged**
